### ISSUE TITLE
Link on What is Awell Orchestration page doesn't work anymore

### ISSUE THREAD

**Issue by rahulkeerthi** [awell-health/developer-hub#72]
From Olivier, on Awell Slack: https://awellhealth.slack.com/archives/C023FQ85FAR/p1662385317716409

`This link on the [What is Awell Orchestration page](https://developers.awellhealth.com/awell-orchestration/docs/getting-started/what-is-awell-orchestration) doesn't work anymore, I think we removed the page`

![image](https://user-images.githubusercontent.com/2485818/188590332-612945a7-1a8e-4e91-9835-d32fa1512021.png)

**Comment by nckhell** [comment]
Resolved.
